# Generated by Django 4.1.4 on 2022-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='quiz/')),
            ],
        ),
        migrations.CreateModel(
            name='OX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='quiz/')),
            ],
        ),
    ]
