# Generated by Django 4.1.4 on 2022-12-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
            ],
        ),
        migrations.AlterField(
            model_name='multichoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/'),
        ),
        migrations.AlterField(
            model_name='ox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/'),
        ),
    ]
