# Generated by Django 4.1.4 on 2022-12-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_shortanswer_alter_multichoice_image_alter_ox_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichoice',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='ox',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='shortanswer',
            old_name='question',
            new_name='question_text',
        ),
    ]
