# Generated by Django 4.1.4 on 2022-12-19 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='solvedby',
            field=models.ManyToManyField(related_name='solvedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='trys',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
