# Generated by Django 4.1.4 on 2022-12-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_question_multichoice_question_text_and_more'),
        ('home', '0004_alter_question_solvedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='MultiChoiceProblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.multichoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='Oxproblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ox'),
        ),
        migrations.AddField(
            model_name='question',
            name='ShortAnswerProblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.shortanswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='qType',
            field=models.CharField(choices=[('OX', 'OX문제'), ('SA', 'Short Answer'), ('MC', 'Multi Choice')], max_length=2, null=True),
        ),
    ]
