# Generated by Django 4.1.4 on 2022-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_question_answer_remove_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='diff',
            field=models.IntegerField(default=0),
        ),
    ]
